services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/meuapp
      - JWT_SECRET=secrettoken
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
